### ISSUE TITLE
Errored Out

### ISSUE THREAD

**Issue by janstadt** [MrYakobo/exif-wrapper#4]
Great script. Ran it on a TB of images and it got half way through before failing due to a folder already potentially existing?

```
fix_metadata  | $ ./bin/run --inputDir '/mnt/GooglePhotos/Albums/Slideshow Pics/' --outputDir '/mnt/GooglePhotos/AlbumsProcessed/Slideshow Pics' --errorDir '/mnt/GooglePhotos/AlbumsError/Slideshow Pics'
fix_metadata  |     Error: If the output directory already exists, it must be empty
fix_metadata  | error Command failed with exit code 2.
fix_metadata  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
fix_metadata  | Traceback (most recent call last):
fix_metadata  |   File "/app/fix_metadata.py", line 125, in <module>
fix_metadata  |     main(args.rootdir)
fix_metadata  |   File "/app/fix_metadata.py", line 118, in main
fix_metadata  |     process_albums(rootdir)
fix_metadata  |   File "/app/fix_metadata.py", line 61, in process_albums
fix_metadata  |     run_mattwilson1024_google_photos_exif(albumdir, outdir, errdir)
fix_metadata  |   File "/app/fix_metadata.py", line 46, in run_mattwilson1024_google_photos_exif
fix_metadata  |     run_mattwilson1024_google_photos_exif(
fix_metadata  |   File "/app/fix_metadata.py", line 25, in run_mattwilson1024_google_photos_exif
fix_metadata  |     sh(
fix_metadata  |   File "/app/fix_metadata.py", line 14, in sh
fix_metadata  |     p.check_returncode()
fix_metadata  |   File "/usr/local/lib/python3.11/subprocess.py", line 502, in check_returncode
fix_metadata  |     raise CalledProcessError(self.returncode, self.args, self.stdout,
fix_metadata  | subprocess.CalledProcessError: Command '['yarn', 'start', '--inputDir', '/mnt/GooglePhotos/Albums/Slideshow Pics/', '--outputDir', '/mnt/GooglePhotos/AlbumsProcessed/Slideshow Pics', '--errorDir', '/mnt/GooglePhotos/AlbumsError/Slideshow Pics']' returned non-zero exit status 2.
```
Anyways, it would be great to update this script so that its able to restart where it failed instead of running it against the entire directory again. Also, if i do run it again, its complaining about the same deal where the folder already exists in the output. Would be cool if it skipped those directories instead of erroring with the assumption that they've already been processed. Or we could look at the AlbumsProcessed directory to determine which folders shouldnt be processed again. Any help would be great! Thanks again!

**Comment by MrYakobo** [comment]
hey there, great feature suggestions.  I recently got kids and don't have the time to lead this project. I'm sorry.

However, lukehmcc forked this project, try reporting this feature request to his repo instead :+1:

https://github.com/lukehmcc/exif-wrapper
